fixed gender color
LoL-pj/LoL-VC pull request #116
Opened 2020-11-21 13:15 UTC by LeonTeraoka

Summary
It turns out that the gender color is not reflected because there was no if statement in show.html.haml to handle the condition.

Result
The gender color will be reflected on the screen after posting.

2020-11-22 05:28 UTC, rutko commented on app/views/teams/show.html.haml
> +              %img.circle.responsive-img{ src: "http://ddragon.leagueoflegends.com/cdn/10.21.1/img/profileicon/#{@team.profile_image}.png", alt: "profile_img"}
The current version of ddragon is 10.23.1 

https://developer.riotgames.com/docs/lol

2020-11-22 05:28 UTC, rutko requested changes
Please fix comment.

2020-11-22 06:11 UTC, LeonTeraoka commented
Thanks for your confirmation.
It's easy to fix it but please give me time because of study.

By the way, your comment "Please fix comment." 
It sounds like my comment is incorrect for the changes.
You can rather say like "Please fix according to my comment"

2020-11-23 03:47 UTC, rutko commented
OK.
I understand that it will take time 😌
And i understood "Please fix according to my comment" 👍

2020-11-23 03:57 UTC, merged